# Generated by Django 3.0.4 on 2020-03-09 10:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jobs.validators.mobile_validator
import jobs.validators.pdf_validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=11, validators=[jobs.validators.mobile_validator.validate_mobile_number])),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('APL', 'Applied'), ('UE', 'Under Evaluation'), ('AF', 'Accepted for First Interview'), ('AS', 'Accepted for Second Interview'), ('AT', 'Accepted for Third Interview'), ('RJ', 'Rejected'), ('OF', 'Offer'), ('CL', 'Canceled')], default='APL', max_length=4)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d/')),
                ('cv', models.FileField(null=True, upload_to='media/%Y/%m/%d/', validators=[jobs.validators.pdf_validator.validate_pdf, django.core.validators.FileExtensionValidator(['pdf'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'applicants',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_open', models.BooleanField(db_index=True, default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('qualifications', models.TextField(blank=True, default='')),
                ('requirements', models.TextField(blank=True, default='')),
                ('good_to_have', models.TextField(blank=True, default='')),
                ('benefits', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.Category')),
            ],
            options={
                'db_table': 'job_postings',
            },
        ),
        migrations.CreateModel(
            name='ApplicantHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APL', 'Applied'), ('UE', 'Under Evaluation'), ('AF', 'Accepted for First Interview'), ('AS', 'Accepted for Second Interview'), ('AT', 'Accepted for Third Interview'), ('RJ', 'Rejected'), ('OF', 'Offer'), ('CL', 'Canceled')], default='APL', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.Applicant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'applicants_history',
            },
        ),
        migrations.AddField(
            model_name='applicant',
            name='job_posting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.JobPosting'),
        ),
    ]
