# Generated by Django 3.0.3 on 2020-02-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='pub_date',
        ),
    ]
