# Generated by Django 3.0.4 on 2020-03-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200313_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
