# Generated by Django 3.0.3 on 2020-02-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='qualifications',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='good_to_have',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(default=''),
        ),
    ]
