# Generated by Django 3.0.3 on 2020-02-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20200224_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('APL', 'Applied'), ('UE', 'Under Evaluation'), ('AF', 'Accepted for First Interview'), ('AS', 'Accepted for Second Interview'), ('AT', 'Accepted for Third Interview'), ('RJ', 'Rejected'), ('OF', 'Offer'), ('CL', 'Canceled')], default='APL', max_length=4),
        ),
    ]
