# Generated by Django 3.0.3 on 2020-02-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_applicant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='picture',
            field=models.ImageField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
