# Generated by Django 3.0.3 on 2020-03-01 13:42

from django.db import migrations, models
import jobs.validators.mobile_validator


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_applicant_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='mobile',
            field=models.CharField(max_length=11, validators=[jobs.validators.mobile_validator.validate_mobile_number]),
        ),
    ]
