# Generated by Django 3.0.3 on 2020-03-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20200304_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='category_id',
            new_name='category',
        ),
    ]
