from .category import CategoryDetailSerializer, CategoryListSerializer
from .job_posting import JobPostingDetailSerializer, JobPostingListSerializer
from .applicant import ApplicantDetailSerializer, ApplicantListSerializer, ApplicantHistorySerializer
